DSTBundesliga/apps/dstffbl/urls.py
from django.urls import path

from DSTBundesliga.apps.dstffbl import views

urlpatterns = [
    path("", views.home, name="home"),
    path("anmeldung/", views.register, name="anmeldung"),
    path("early-bird/", views.early_bird, name="early-bird"),
    path(
        "accept_invite/<str:registration_id>/",
        views.confirm_registration,
        name="accept_invite",
    ),
    path("login/", views.login, name="login"),
    path("profile/", views.profile, name="profile"),
    path("resend_invite", views.resend_invite, name="resend_invite"),
]

DSTBundesliga/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

from DSTBundesliga import views

admin.autodiscover()

urlpatterns = [
    path(
        "", include(("DSTBundesliga.apps.dstffbl.urls", "dstffbl"), namespace="dstffbl")
    ),
    path("auth/", include("django.contrib.auth.urls")),
    path("accounts/", include("allauth.urls")),
    path("leagues/", include("DSTBundesliga.apps.leagues.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("admin/", admin.site.urls),
    url(r"^shared/", include("filer.urls")),
    path("regelwerk/", views.regelwerk),
    re_path(r"^", include("cms.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/breadcrumb.html
{% if ancestors|length > 1 %}
<ul class="breadcrumb {% if 'CFFC' in request.path %}CFFC{% elif 'AFFC' in request.path %}AFFC{% endif %}">
    {% for ance in ancestors %}
    <li class="item">
        {% if not forloop.last %}
        <a href="{{ ance.get_absolute_url }}">{% if ance.get_menu_title == 'Sued' %}Süd{% else %}{{ ance.get_menu_title }}{% endif %}</a>
        {% else %}
        <span class="active">{% if ance.get_menu_title == 'Sued' %}Süd{% else %}{{ ance.get_menu_title }}{% endif %}</span>
        {% endif %}
    </li>
    {% endfor %}
</ul>
{% endif %}

templates/home.html
{% extends 'base.html' %}
{% load cms_tags %}

{% block content %}
{% placeholder "content" %}
{% endblock %}

templates/legend.html
<div class="legend-container">
    <ul>
        <li><span class="legend-symbol">x</span><span class="legend-explain">Playoff-Platz gesichert</span></li>
        <li><span class="legend-symbol">o</span><span class="legend-explain">Entscheidung offen</span></li>
    </ul>
</div>

templates/menu.html
{% load menu_tags socialaccount %}

{% for child in children %}
<div class="item league-menu-node menu-node-{{child.id}} {% if child.selected or child.ancestor %}selected {% endif %}{% if child.children %}droppable {% endif %}{{ child.attr.li_class }}">
    <a href="{{ child.attr.redirect_url|default:child.get_absolute_url }}">{{ child.get_menu_title }}</a>
</div>
{% endfor %}
<div class="item league-menu-node right border-left}">
    {% if user.is_authenticated %}
    <a href="{% url 'logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'dstffbl:login' %}?next={{ request.path }}">Login</a>
    {% endif %}
</div>

templates/tables_base.html
{% extends 'base.html' %}